### ISSUE TITLE
Error in fz-File (fritzing 0.9.3b on Windows 10)

### ISSUE THREAD

**Issue by evildrummer** [ThomDietrich/SenseoWifi#10]
![error fritzing](https://user-images.githubusercontent.com/16805842/42751691-da3ebaa0-88eb-11e8-9289-3cc42101ce60.png)

**Comment by ThomDietrich** [comment]
Nope sorry must be an issue with your system or download. Just tested with a fresh Fritzing and file download myself.

**Comment by evildrummer** [comment]
Hm,

i tested it on Win7 and 10 (x86 and x64 Version). :-/ 

Can you upload a fzz or gerber version of the File? Then i dont need Fritzing anymore.
Fzz is the supported type when i want to upload it on their Website (aisler.net). 

Thanks

**Comment by ThomDietrich** [comment]
[SenseoWifi-PCB_GERBER.zip](https://github.com/ThomDietrich/SenseoWifi/files/2197631/SenseoWifi-PCB_GERBER.zip)

This is the file I last used to produce PCBs I'm currently using. Be aware that I realized later on that two connectors are mission in this version https://github.com/ThomDietrich/SenseoWifi/issues/8#issuecomment-389109496

**Comment by ThomDietrich** [comment]
You should try once again. Your error sounds like you did something wrong when downloading the file...

**Comment by evildrummer** [comment]
Well. Finally i was able to open it :)

but!..... i´m not sure if my added pins are well placed :) 
![added pins](https://user-images.githubusercontent.com/16805842/42761410-bb428ede-890d-11e8-9bf9-9d9c7c1013b4.png)

If you´re giving me an ok i´ll do the pull request. But first i have to check out what that means :) I´m new on github.

**Comment by ThomDietrich** [comment]
Looks fine to me. I myself was hoping to not extend the size of the PCB... you know what, give me a sec.

**Comment by ThomDietrich** [comment]
![grafik](https://user-images.githubusercontent.com/2870104/42765658-d150fed0-8918-11e8-95e6-02e39f03f6e5.png)

**Comment by ThomDietrich** [comment]
[SenseoWifi_PCB_v1.7_Extended_Gerber.zip](https://github.com/ThomDietrich/SenseoWifi/files/2198093/SenseoWifi_PCB_v1.7_Extended_Gerber.zip)

**Comment by ThomDietrich** [comment]
The new connectors on the bottom left are for the Reset button and for VCC from the step down converter. Enjoy! Let me know if you need more help!

**Comment by mboremski** [comment]
@ThomDietrich might be closed.. not? :-)

**Comment by ThomDietrich** [comment]
Sounds like it. Thanks ;)
