### ISSUE TITLE
Homebridge?

### ISSUE THREAD

**Issue by solbadguy2010** [ThomDietrich/SenseoWifi#22]
Hi,
i really would like to get my Senso in Homekit by unsing Homebridge.
Is this possible? Could somebody help me with this?

Existing Homebridge is running and Hardware modifications are not a problem. Software is the part i am bad at :-)

**Comment by ThomDietrich** [comment]
I think you can connect Homebridge with openHAB and an openHAB connection with the machine is documented. Not sure if this would be the best or easiest or feasible solution for you

**Comment by solbadguy2010** [comment]
Hi,
I think this would work in some way. Every openHAB button would be an Single Homekit object. The idea behind an native homebridge plugin is, that you than have one homekit Object with all the functionality.
