### ISSUE TITLE
Change boolean MQTT values fom true/false to ON/OFF (?)

### ISSUE THREAD

**Issue by mboremski** [ThomDietrich/SenseoWifi#23]
As diskussed in #19 it might be better to change the codebase to send ON/OFF instead of true/false for boolean values.

**Comment by ThomDietrich** [comment]
Also related to the Homie convention and the upgrade to Homie v3.x.

**Comment by ThomDietrich** [comment]
Hey @mboremski I'm currently updating to Homie 3, however as booleans are defined as "true" or "false" I'm inclined to reject this request. Please remind me when I am wrong :) Thanks!

https://homieiot.github.io/specification/#boolean
