### ISSUE TITLE
Stop brewing if cup is removed

### ISSUE THREAD

**Issue by mboremski** [ThomDietrich/SenseoWifi#24]
I tried out what happens if the cup is removed while coffee is brewed.
(Maybe cup falls of ore someone is in hurry.. ;-) )

Maybe someone can implement a feature that switches the machine off in such cases?

**Comment by ThomDietrich** [comment]
Interesting edge case, I'm not sure if we want to actively react to this event. If the user removes the cup they may just as well turn the machine off.

**Comment by ThomDietrich** [comment]
@mboremski want to provide a PR? P.S. I've updated the code to Homie 3, check it out.

**Comment by ThomDietrich** [comment]
Hey, just in case you are still using the machine. I did push some considerable updates the last couple of days.
Regarding the request here, I feel this is not as useful. If the user decides to remove the cup, they probably know what they are doing...
