### ISSUE TITLE
Compile failing

### ISSUE THREAD

**Issue by davidw3591** [ThomDietrich/SenseoWifi#25]
I'm trying to compile the code in VisualStudioCode woth PlatformIO. Unfortunately the build failes with a lot off errors regarding Homie.
![Knipsel](https://user-images.githubusercontent.com/22191954/70752694-6dbf1b80-1d33-11ea-92e0-75b2069c4774.JPG)

I'm just getting started with VSC/PIO, these are the steps I did to get to the failing point:
* Downloaded zip file with GitHub SenseoWifi code
* Unzipped and opened SenseoWifi-master folder in VSC
* Installed a bunch of libraries in PIO:
*** ArduinoJSON...
*** AsyncMqttClient
*** AsyncTCP
*** Bounce2
* Compile with PlatformIO in VSC

**UPDATE**: On second look it's pretty obvious ArduinoJson had to be version 5. Uninstalled version 6 and the issue was resolved. Code is now compiling sccesfully.

**Comment by ThomDietrich** [comment]
Congrats you've solved this. Partly my fault for not updating to the latest Homie version yet...
Please feel encouraged to provide whatever you come up with as improvements to the code
