### ISSUE TITLE
Arduino Core fix

### ISSUE THREAD

**Issue by ThomDietrich** [ThomDietrich/SenseoWifi#29]
@pattyland  wrote in https://github.com/ThomDietrich/SenseoWifi/pull/28:

> Hi,
> 
> there seems to be [problems with newer version of arduino core](https://github.com/esp8266/Arduino/issues/6127). 
> My D1 Mini would crash at boot with a `ISR not in IRAM` error. 
> 
> This PR ist the [quick fix](https://github.com/esp8266/Arduino/issues/6127), [this is the longer (and better?) fix](https://github.com/esp8266/Arduino/issues/6127#issuecomment-497785103) I guess.
> 
> Best regards
> Sören

**Comment by ThomDietrich** [comment]
@pattyland did you try the `ICACHE_RAM_ATTR` workaround?

**Comment by pattyland** [comment]
No, it was late at night and pinning the platform version was quicker 🙈
