### ISSUE TITLE
senseo-wifi.map is missed

### ISSUE THREAD

**Issue by Miro1980** [ThomDietrich/SenseoWifi#31]
Hi,
really nice project.
May I ask you for the file "senseo-wifi.map"? It is mentioned in your openhab code.
String KU_Senseo_OutOfWater    "OutOfWater"  {channel="mqtt:topic:SenseoWiFi:OutOfWater" [profile="transform:MAP", function="senseo-wifi.map"]}

Further I like to ask you if you tried to combine your project with Alexa?
How did you proceed?

Thanks.

**Comment by ThomDietrich** [comment]
Hey Miro!
Sure thing. You can find it here: https://github.com/ThomDietrich/openhab-config/blob/master/transform/senseo-wifi.map Would you please be so kind and create a Pull Request against the README.md to include it?

Alexa is pretty easy after you have a working connection between openHAB<>SenseoWifi and openHAB<>Alexa. What you want to do is define a Alexa command like "Alexa, prepare a coffee" and link it to an openHAB rule to send "1cup" to "KU_Senseo_Brew". I can share more details if this is not yet clear
