### ISSUE TITLE
Build endet mit Abhängigkeitsfehlern

### ISSUE THREAD

**Issue by MichiW1** [ThomDietrich/SenseoWifi#36]
Hallo ThomDietrich,

du hast ein tolles Projekt hier, das ich unbedingt nachbauen wollte.
Leider habe ich nicht ganz so tiefe Programmierkenntnisse, habe aber deine Anleitung Schritt für Schritt durchgearbeitet.

Wenn ich im VS Code den Build über PlatformIO starte, kommt folgender Fehler.
Ich habe keine Ahnung, warum die Abhängigkeiten der Libraries nicht richtig aufgelöst werden... habe alles versucht und bin am Verzweifeln. Was mache ich falsch?

> Executing task in folder SenseoWifi: C:\Users\HP\.platformio\penv\Scripts\platformio.exe run <

Processing senseo-wifi (platform: espressif8266; board: d1_mini; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 2.6.2 > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.20704.0 (2.7.4)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.20800.0 (2.8.0)
 - toolchain-xtensa 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
LibraryManager: Installing homie-esp8266
git version 2.28.0.windows.1
Cloning into 'C:\Users\HP\Documents\Arduino\SenseoWifi\.pio\libdeps\senseo-wifi\_tmp_installing-rc1c2hz6-package'...
HEAD is now at cfb3346 Fix mentions of develop-v3 branch (#658)
Homie @ cfb3346 has been successfully installed!
Installing dependencies
Looking for ArduinoJson library in registry
Found: https://platformio.org/lib/show/64/ArduinoJson
LibraryManager: Installing id=64 @ ^6.11.4
Using cache: C:\Users\HP\.platformio\.cache\4f\ad2aa21b2ac287f82c72bba98a5ef04f

Unpacking  [############------------------------]   35%
Unpacking  [#############-----------------------]   36%
Unpacking  [#############-----------------------]   37%
Unpacking  [#############-----------------------]   38%
Unpacking  [##############----------------------]   38%
Unpacking  [##############----------------------]   39%
Unpacking  [##############----------------------]   40%
Unpacking  [##############----------------------]   41%
Unpacking  [###############---------------------]   41%
Unpacking  [###############---------------------]   42%
Unpacking  [###############---------------------]   43%
Unpacking  [################--------------------]   44%
Unpacking  [################--------------------]   45%
Unpacking  [################--------------------]   46%
Unpacking  [#################-------------------]   47%
Unpacking  [#################-------------------]   48%
Unpacking  [#################-------------------]   49%
Unpacking  [##################------------------]   50%
Unpacking  [##################------------------]   51%
Unpacking  [##################------------------]   52%
Unpacking  [###################-----------------]   53%
Unpacking  [###################-----------------]   54%
Unpacking  [####################----------------]   55%
Unpacking  [####################----------------]   56%
Unpacking  [####################----------------]   57%
Unpacking  [####################----------------]   58%
Unpacking  [#####################---------------]   58%
Unpacking  [#####################---------------]   59%
Unpacking  [#####################---------------]   60%
Unpacking  [######################--------------]   61%
Unpacking  [######################--------------]   62%
Unpacking  [######################--------------]   63%
Unpacking  [#######################-------------]   64%
Unpacking  [#######################-------------]   65%
Unpacking  [#######################-------------]   66%
Unpacking  [########################------------]   66%
Unpacking  [########################------------]   67%
Unpacking  [########################------------]   68%
Unpacking  [########################------------]   69%
Unpacking  [#########################-----------]   69%
Unpacking  [#########################-----------]   70%
Unpacking  [#########################-----------]   70%  00:00:00
Unpacking  [#########################-----------]   71%  00:00:00
Unpacking  [##########################----------]   72%  00:00:00
Unpacking  [##########################----------]   73%  00:00:00
Unpacking  [##########################----------]   74%  00:00:00
Unpacking  [###########################---------]   75%  00:00:00
Unpacking  [###########################---------]   76%  00:00:00
Unpacking  [###########################---------]   77%  00:00:00
Unpacking  [############################--------]   77%  00:00:00
Unpacking  [############################--------]   78%  00:00:00
Unpacking  [############################--------]   79%  00:00:00
Unpacking  [############################--------]   80%  00:00:00
Unpacking  [#############################-------]   80%  00:00:00
Unpacking  [#############################-------]   81%  00:00:00
Unpacking  [#############################-------]   82%  00:00:00
Unpacking  [##############################------]   83%  00:00:00
Unpacking  [##############################------]   84%  00:00:00
Unpacking  [##############################------]   85%  00:00:00
Unpacking  [###############################-----]   86%  00:00:00
Unpacking  [###############################-----]   87%  00:00:00
Unpacking  [###############################-----]   88%  00:00:00
Unpacking  [################################----]   88%  00:00:00
Unpacking  [################################----]   89%  00:00:00
Unpacking  [################################----]   90%  00:00:00
Unpacking  [################################----]   91%  00:00:00
Unpacking  [#################################---]   91%  00:00:00
Unpacking  [#################################---]   92%  00:00:00
Unpacking  [#################################---]   93%  00:00:00
Unpacking  [##################################--]   94%  00:00:00
Unpacking  [##################################--]   95%  00:00:00
Unpacking  [##################################--]   96%  00:00:00
Unpacking  [###################################-]   97%  00:00:00
Unpacking  [###################################-]   98%  00:00:00
Unpacking  [###################################-]   99%  00:00:00
Unpacking  [####################################]  100%
ArduinoJson @ 6.16.1 has been successfully installed!
Looking for AsyncMqttClient library in registry
Found: https://platformio.org/lib/show/346/AsyncMqttClient
LibraryManager: Installing id=346 @ ^0.8.0
Using cache: C:\Users\HP\.platformio\.cache\63\83f24bfe072da77a2676219044370a63

Unpacking  [##################################--]   96%
Unpacking  [###################################-]   98%
Unpacking  [####################################]  100%
AsyncMqttClient @ 0.8.2 has been successfully installed!
Installing dependencies
Looking for ESPAsyncTCP library in registry
Found: https://platformio.org/lib/show/305/ESPAsyncTCP
LibraryManager: Installing id=305 @ 1.2.0
Using cache: C:\Users\HP\.platformio\.cache\d9\cbc13db98b326acd412892db90b8e7d9
ESPAsyncTCP @ 1.2.0 has been successfully installed!
Looking for AsyncTCP library in registry
Found: https://platformio.org/lib/show/1826/AsyncTCP
LibraryManager: Installing id=1826 @ ^1.0.0
Using cache: C:\Users\HP\.platformio\.cache\8f\74372f406cb2e549f3eb2773b739d38f
AsyncTCP @ 1.1.1 has been successfully installed!
Looking for Bounce2 library in registry
Found: https://platformio.org/lib/show/1106/Bounce2
LibraryManager: Installing id=1106 @ ^2.1.0
Using cache: C:\Users\HP\.platformio\.cache\4f\6ce5eb13ab365e3a90a49dc183d5194f

Unpacking  [#################-------------------]   49%
Unpacking  [##################------------------]   50%
Unpacking  [##################------------------]   51%
Unpacking  [##################------------------]   52%
Unpacking  [###################-----------------]   53%
Unpacking  [###################-----------------]   54%
Unpacking  [####################----------------]   55%
Unpacking  [####################----------------]   56%
Unpacking  [####################----------------]   57%
Unpacking  [#####################---------------]   58%
Unpacking  [#####################---------------]   59%
Unpacking  [#####################---------------]   60%
Unpacking  [######################--------------]   61%
Unpacking  [######################--------------]   62%
Unpacking  [######################--------------]   63%
Unpacking  [#######################-------------]   64%
Unpacking  [#######################-------------]   65%
Unpacking  [########################------------]   66%
Unpacking  [########################------------]   67%
Unpacking  [########################------------]   68%
Unpacking  [########################------------]   69%
Unpacking  [#########################-----------]   69%
Unpacking  [#########################-----------]   70%
Unpacking  [#########################-----------]   71%
Unpacking  [##########################----------]   72%
Unpacking  [##########################----------]   73%
Unpacking  [##########################----------]   74%
Unpacking  [###########################---------]   75%
Unpacking  [###########################---------]   76%
Unpacking  [############################--------]   77%
Unpacking  [############################--------]   78%
Unpacking  [############################--------]   79%
Unpacking  [############################--------]   80%
Unpacking  [#############################-------]   80%
Unpacking  [#############################-------]   81%
Unpacking  [#############################-------]   82%
Unpacking  [##############################------]   83%
Unpacking  [##############################------]   84%
Unpacking  [##############################------]   85%
Unpacking  [###############################-----]   86%
Unpacking  [###############################-----]   87%
Unpacking  [###############################-----]   88%
Unpacking  [################################----]   88%
Unpacking  [################################----]   89%
Unpacking  [################################----]   90%
Unpacking  [################################----]   91%
Unpacking  [#################################---]   92%
Unpacking  [#################################---]   93%  00:00:00
Unpacking  [##################################--]   94%  00:00:00
Unpacking  [##################################--]   95%  00:00:00
Unpacking  [##################################--]   96%  00:00:00
Unpacking  [###################################-]   97%  00:00:00
Unpacking  [###################################-]   98%  00:00:00
Unpacking  [###################################-]   99%  00:00:00
Unpacking  [####################################]  100%
Bounce2 @ 2.55 has been successfully installed!
Looking for ESP Async WebServer library in registry
Found: https://platformio.org/lib/show/306/ESP Async WebServer
LibraryManager: Installing id=306
Using cache: C:\Users\HP\.platformio\.cache\1d\f4ff895b8eec29acc52f25215402c91d
ESP Async WebServer @ 1.2.3 has been successfully installed!
Installing dependencies
Looking for ESPAsyncTCP library in registry
Found: https://platformio.org/lib/show/305/ESPAsyncTCP
LibraryManager: Installing id=305
Using cache: C:\Users\HP\.platformio\.cache\3c\69ec8d45eebc4e13c137f6bf4cd5f53c
ESPAsyncTCP @ 1.2.2 has been successfully installed!
Looking for AsyncTCP library in registry
Found: https://platformio.org/lib/show/1826/AsyncTCP
LibraryManager: Installing id=1826
Using cache: C:\Users\HP\.platformio\.cache\8f\74372f406cb2e549f3eb2773b739d38f
AsyncTCP @ 1.1.1 has been successfully installed!
Looking for Hash library in registry
Warning! Library `{'name': 'Hash', 'platforms': ['espressif8266']}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'name': 'Hash', 'platforms': ['espressif8266']}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.
Found 36 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Homie> 3.0.0 #cfb3346
|   |-- <ArduinoJson> 6.16.1
|   |-- <AsyncMqttClient> 0.8.2
|   |   |-- <ESPAsyncTCP> 1.2.2
|   |   |   |-- <ESP8266WiFi> 1.0
|   |-- <Bounce2> 2.55
|   |-- <ESP Async WebServer> 1.2.3
|   |   |-- <ESPAsyncTCP> 1.2.2
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <Hash> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ArduinoJson> 6.16.1
|   |-- <Ticker> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <DNSServer> 1.1.1
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266HTTPClient> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESPAsyncTCP> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
Building in release mode
Compiling .pio\build\senseo-wifi\src\Cup.cpp.o
Compiling .pio\build\senseo-wifi\src\SenseoControl.cpp.o
Compiling .pio\build\senseo-wifi\src\SenseoLed.cpp.o
Compiling .pio\build\senseo-wifi\src\SenseoSM.cpp.o
In file included from C:\Users\HP\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:238:0,
                 from .pio\libdeps\senseo-wifi\Homie\src/Homie.hpp:3,
                 from .pio\libdeps\senseo-wifi\Homie\src/Homie.h:4,
                 from src\Cup.h:9,
                 from src\Cup.cpp:7:
c:\users\hp\.platformio\packages\toolchain-xtensa\xtensa-lx106-elf\include\c++\4.8.2\algorithm:60:30: fatal error: utility: No 
such file or directory
 #include <utility> // UK-300.
                              ^
compilation terminated.
*** [.pio\build\senseo-wifi\src\Cup.cpp.o] Error 1
In file included from C:\Users\HP\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:238:0,
                 from .pio\libdeps\senseo-wifi\Homie\src/Homie.hpp:3,
                 from .pio\libdeps\senseo-wifi\Homie\src/Homie.h:4,
                 from src\SenseoLed.h:9,
                 from src\SenseoLed.cpp:7:
c:\users\hp\.platformio\packages\toolchain-xtensa\xtensa-lx106-elf\include\c++\4.8.2\algorithm:60:30: fatal error: utility: No 
such file or directory
 #include <utility> // UK-300.
                              ^
compilation terminated.
In file included from C:\Users\HP\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:238:0,
                 from .pio\libdeps\senseo-wifi\Homie\src/Homie.hpp:3,
                 from .pio\libdeps\senseo-wifi\Homie\src/Homie.h:4,
                 from src\SenseoControl.h:9,
                 from src\SenseoControl.cpp:7:
c:\users\hp\.platformio\packages\toolchain-xtensa\xtensa-lx106-elf\include\c++\4.8.2\algorithm:60:30: fatal error: utility: No 
such file or directory
 #include <utility> // UK-300.
                              ^
compilation terminated.
In file included from C:\Users\HP\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:238:0,
                 from .pio\libdeps\senseo-wifi\Homie\src/Homie.hpp:3,
                 from .pio\libdeps\senseo-wifi\Homie\src/Homie.h:4,
                 from src\SenseoSM.h:9,
                 from src\SenseoSM.cpp:7:
c:\users\hp\.platformio\packages\toolchain-xtensa\xtensa-lx106-elf\include\c++\4.8.2\algorithm:60:30: fatal error: utility: No 
such file or directory
 #include <utility> // UK-300.
                              ^
compilation terminated.
*** [.pio\build\senseo-wifi\src\SenseoControl.cpp.o] Error 1
*** [.pio\build\senseo-wifi\src\SenseoLed.cpp.o] Error 1
*** [.pio\build\senseo-wifi\src\SenseoSM.cpp.o] Error 1
================================================= [FAILED] Took 38.17 seconds =================================================
The terminal process "C:\Users\HP\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

Danke für deine Hilfe,
Michael

**Comment by MichiW1** [comment]
Hallo zusammen,
ich habe mein Problem nun selbst lösen können:

Es gibt wohl einen größeren Fehler bei der Platform.io extension für MS VSCode unter einem Windows Rechner. Einige Dateien und Verzeichnisse werden bei der Installation nicht angelegt. Unter Linux läuft es hingegen perfekt.

Konkret geht es um die Inhalte im Verzeichnis: 
C:\Users\{username}\.platformio\packages\toolchain-xtensa\xtensa-lx106-elf\include\c++\4.8.2
Ich habe diesen Ordner einfach aus der erfolgreichen Linux-Installation (liegt dort im home-Verzeichnis unter gleicher Struktur) mit allen Inhalten in den Windows-Ordner kopiert und schon läuft der Build durch... 

Sicher keine schöne Lösung, aber es geht. 
(Neuinstallation von platform.io unter Windows etc. hatte ich vorher alles vergeblich versucht :-()

Grüße, Michael

**Comment by ThomDietrich** [comment]
Hey Michael! Freut mich dass du das Problem lösen konntest und auch für den nächsten Nutzer mit dem Problem dokumentiert hast. Danke dafür. Viele Grüße!
