### ISSUE TITLE
Out of water when Brewing

### ISSUE THREAD

**Issue by miit86** [ThomDietrich/SenseoWifi#38]
Hello,

nice project, I made my own PCB and it works almost correct.
I have an 7863 machine. When the machine is brewing it gives me the out of water alert.

I think I have to adjust the static "const int pulseDurLedSlow = 1000;" to "static const int pulseDurLedSlow = 2000;"
My machine blinks once every 2 seconds when its heating or brewing.

I am unable to see how many blinks the machine does when "out of water"
How can I enable: // Measure your timings by activating debugging in ledChangedRoutine()

Greetz Michel

**Comment by ThomDietrich** [comment]
Hey Michel,
the line you are looking for is https://github.com/ThomDietrich/SenseoWifi/blob/9264955691747e21e436271c5656ed9295bbca57/src/SenseoLed.cpp#L31
As you can see, it is already active and the output is written to the serial console (USB)
