### ISSUE TITLE
TCRT5000 disable

### ISSUE THREAD

**Issue by ALutz273** [ThomDietrich/SenseoWifi#48]
the project is very good and I have implemented everything except the TCRT5000 sensor. 
How can I turn this off in the firmware?

**Comment by ThomDietrich** [comment]
Hey great to hear :)
There is actually an option for that so you can just disable it after flashing the firmware. You need to tick off an option on the setup screen.

Alternatively check this file https://github.com/ThomDietrich/SenseoWifi/blob/master/src/SenseoWifi.cpp for `CupDetectorAvailableSetting`
Beware that even though its an option, I didn't test it for a long time.

And just so I said it once. The TCRT5000 as part of this project adds quite a lot. Consider adding it :)

Best!
