### ISSUE TITLE
List of hardware

### ISSUE THREAD

**Issue by mull0r** [ThomDietrich/SenseoWifi#50]
Maybe (probably) I am an idiot, but where can I get my hands on a compatible PCB? I am not unfamiliar with flashing and soldering, however I am unfamiliar with custom PCBS. 

Is it possible to provide the list of requirements and include one or more examples where to get the hardware? 

I am located in The Netherlands by the way.

**Comment by bjornmorsman** [comment]
Ik heb nog 4 v1.7 pcb’s liggen, dus als je wilt kun je deze wel overnemen.

**Comment by ThomDietrich** [comment]
Thanks @bjornmorsman,

generally you can just order the PCB to be produced. The gerber files you need to do so can be found here: https://github.com/ThomDietrich/SenseoWifi/tree/master/SenseoWifi-PCB

A cheap international option is https://www.pcbway.com but there are more than enough local option, if you want to suport those.

In additon to the PCB you need the electrical components to be soldered on, the list is in the README. Let us know if you need more help.

**Comment by timvanhulten** [comment]
> 

Zou ik er twee van je kunnen overnemen?

**Comment by bjornmorsman** [comment]
Hoi Tim,

10tje exclusief verzendkosten? Kun je je daarin vinden?

Groet, Bjorn

**Comment by timvanhulten** [comment]
Ja, is prima. Kan gewoon met briefpost neem ik aan. Kunt het verzenden naar Valeriusstraat 4A, 5151LP te Drunen. Kunt me toevoegen op whatsapp voor een tikkie. Via 0622522140.

Bvd

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by TonKro** [comment]
Heb je er nog liggen mogelijk? Ik heb er maar 1 of 2 nodig.

**Comment by bjornmorsman** [comment]
Ik zal zo eens in mijn hobby la kijken, heb er zeker nog 1. De 2de moet ik even nakijken. Wil je de rest van de componenten er ook bij?

mvg,

Bjorn

**Comment by TonKro** [comment]
Ik hoor graag. Componten is zeker zo makkelijk maar kan die eventueel ook bestellen.

**Comment by TonKro** [comment]
Ben je er nog aan toegekomen?

**Comment by timvanhulten** [comment]
Ik heb de print toevallig vorige week afgemaakt. Mistte de 1.5k ohm zekering, die inmiddels is toegevoegd. Volgende week bouw ik hem denk ik in. Mits ik niet weer een of ander project tussendoor oppak.



Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TonKro** [comment]
Als ik je goed begrijp heb je geen (bestuukte) print meer over?

**Comment by timvanhulten** [comment]
Heb er nog 1 over

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TonKro** [comment]
Die wil ik graag overnemen van je. Laat maar weten hoe we dit kunnen regelen

**Comment by kgraefe** [comment]
Does someone still has a PCB laying around? I'm located in Germany.

**Comment by ThomDietrich** [comment]
Hey Konrad, I still have a bunch. I can send you one in a letter. Need to check but I think it is version 1.6 of the PCB, which is still already good enough. The later versions were just for perfection

**Comment by qwibbert** [comment]
I'm from Belgium and I'm looking for the PCB board. I thought it would be easier and cheaper to just buy one off of someone who got multiple copies already printed.  Anyone who has a spare board laying around?
