### ISSUE TITLE
Upload Problem

### ISSUE THREAD

**Issue by mrhary** [ThomDietrich/SenseoWifi#65]
hecking size .pio/build/d1_mini/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [======    ]  55.2% (used 45212 bytes from 81920 bytes)
Flash: [======    ]  59.0% (used 616180 bytes from 1044464 bytes)
Building .pio/build/d1_mini/firmware.bin
Creating BIN file ".pio/build/d1_mini/firmware.bin" using "/home/harald/.platformio/packages/framework-arduinoespressif8266@3.30101.0/bootloaders/eboot/eboot.elf" and ".pio/build/d1_mini/firmware.elf"
Configuring upload protocol...
AVAILABLE: espota, esptool
CURRENT: upload_protocol = esptool
Looking for upload port...
Using manually specified: /dev/ttyUSB1
Uploading .pio/build/d1_mini/firmware.bin
usage: esptool [-h] [--chip {auto,esp8266,esp32,esp32s2,esp32s3beta2,esp32c3}]
               [--port PORT] [--baud BAUD]
               [--before {default_reset,no_reset,no_reset_no_sync}]
               [--after {hard_reset,soft_reset,no_reset}] [--no-stub]
               [--trace] [--override-vddsdio [{1.8V,1.9V,OFF}]]
               [--connect-attempts CONNECT_ATTEMPTS]
               {load_ram,dump_mem,read_mem,write_mem,write_flash,run,image_info,make_image,elf2image,read_mac,chip_id,flash_id,read_flash_status,write_flash_status,read_flash,verify_flash,erase_flash,erase_region,version,get_security_info}
               ...
esptool: error: unrecognized arguments: --auth=senseo
*** [upload] Error 2
======================================== [FAILED] Took 113.80 seconds ========================================

 *  The terminal process "platformio 'run', '--target', 'upload'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

Wenn ich das Upload_Flags deaktiviere läuft es durch, jedoch komm ich trotzdem nicht auf die Settings.html

**Comment by ThomDietrich** [comment]
Hallo @mrhary,
hast du das Problem lösen können? Eine Fehlerursache die man dokumentieren sollte?

**Comment by mrhary** [comment]
War mein Fehler in Vision Studio, bin in dem Programm ein Neuling

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
