### ISSUE TITLE
what plug to power this

### ISSUE THREAD

**Issue by VinceMasuka** [ThomDietrich/SenseoWifi#8]
Hi

Sorry for the maybe dumb question, but looking at the board layout, the used pins and comparing lab plus final pictures of yours...
What plug(s) are responsible for powering (5V and GND) this board?
Do you power it solely by USB?
And if so: Did you connect that USB directly to the 220V to 5V AC-DC step down module?

Thanks!

Regards
Vince

**Comment by ThomDietrich** [comment]
Good question, we left the USB port open for debugging and connected the step down module directly to `GND` and `5V`. Now that you ask: I am not quite sure why there are no dedicated pins for this purpose.
Looking at the pictures, I believe that the hacked extra connectors on the side serve that purpose in our machine. https://raw.githubusercontent.com/ThomDietrich/SenseoWifi/master/images/DSC09604.jpg
If you build and soldered your own PCB, it should be easy to add additional pins. As for our provided PCB design: Yes we should improve it...
